apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: be
  name: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: back-end
          image: sakit333/backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
